# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version-check.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='version-check.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13version-check.proto\"Y\n\x13VersionCheckRequest\x12\x17\n\x0f\x66older_location\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\x05\x12\x15\n\rrequest_token\x18\x03 \x01(\t\"]\n\x14VersionCheckResponse\x12\x16\n\x0elatest_version\x18\x01 \x01(\t\x12\x17\n\x0f\x63urrent_version\x18\x02 \x01(\t\x12\x14\n\x0cneed_upgrade\x18\x03 \x01(\x08\x32N\n\x0fVersionCheckSrv\x12;\n\x0cVersionCheck\x12\x14.VersionCheckRequest\x1a\x15.VersionCheckResponseb\x06proto3'
)




_VERSIONCHECKREQUEST = _descriptor.Descriptor(
  name='VersionCheckRequest',
  full_name='VersionCheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='folder_location', full_name='VersionCheckRequest.folder_location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='VersionCheckRequest.request_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_token', full_name='VersionCheckRequest.request_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=112,
)


_VERSIONCHECKRESPONSE = _descriptor.Descriptor(
  name='VersionCheckResponse',
  full_name='VersionCheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latest_version', full_name='VersionCheckResponse.latest_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_version', full_name='VersionCheckResponse.current_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='need_upgrade', full_name='VersionCheckResponse.need_upgrade', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=207,
)

DESCRIPTOR.message_types_by_name['VersionCheckRequest'] = _VERSIONCHECKREQUEST
DESCRIPTOR.message_types_by_name['VersionCheckResponse'] = _VERSIONCHECKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VersionCheckRequest = _reflection.GeneratedProtocolMessageType('VersionCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONCHECKREQUEST,
  '__module__' : 'version_check_pb2'
  # @@protoc_insertion_point(class_scope:VersionCheckRequest)
  })
_sym_db.RegisterMessage(VersionCheckRequest)

VersionCheckResponse = _reflection.GeneratedProtocolMessageType('VersionCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONCHECKRESPONSE,
  '__module__' : 'version_check_pb2'
  # @@protoc_insertion_point(class_scope:VersionCheckResponse)
  })
_sym_db.RegisterMessage(VersionCheckResponse)



_VERSIONCHECKSRV = _descriptor.ServiceDescriptor(
  name='VersionCheckSrv',
  full_name='VersionCheckSrv',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=209,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='VersionCheck',
    full_name='VersionCheckSrv.VersionCheck',
    index=0,
    containing_service=None,
    input_type=_VERSIONCHECKREQUEST,
    output_type=_VERSIONCHECKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VERSIONCHECKSRV)

DESCRIPTOR.services_by_name['VersionCheckSrv'] = _VERSIONCHECKSRV

# @@protoc_insertion_point(module_scope)
